/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'luisvelasco' at '24/02/16 8:22' with Gradle 2.6
 *
 * @author luisvelasco, @date 24/02/16 8:22
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
